### ISSUE TITLE
Remove resourcespace.yml and parameters.yml

### ISSUE THREAD

**Issue by netsensei** [VlaamseKunstcollectie/Imagehub#3]
The Github repository contains `app/config/resourcespace.yml` and `app/config/parameters.yml` files. These files are environment specific => the API key for resourcespace will differ per person, per installation, per environment,...

The goal of the resourcespace.yml.dist file is to have a generic template which can be copied and modified. The YAML files themselves shouldn't be commited in the main vanilla Github repository. The YAML files stay on the local machines.

We need to do these steps:

* Remove resourcespace.yml and parameters.yml from the Github repo
* Add them to the `.gitignore` file to avoid them getting committed

**Comment by Kitania** [comment]
I have removed parameters.yml and added it to .gitignore. resourcespace.yml contains a lot of non-environment specific parameters so I have decided to keep that file in the repository, but I did move all environment-specific parameters in resourcespace.yml to parameters.yml.dist.
This will obviously break the current live version, so in order to get a proper parameters.yml file (without having to set up the Imagehub all over again), you can check https://github.com/VlaamseKunstcollectie/Imagehub/blob/685bcc151dd76d8051722864fd2fd6e72323e250/app/config/parameters.yml, although you'll still need to change a few parameters such as the API key and password.
