### ISSUE TITLE
manifests.json are not IIIF Presentation API 2.1 valid

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#5]
The manifest.json files created from the generatemanifests command are currently not valid following the 2.1 Presentation API Spec. 

You can validate manifests by entering a manifest URL here: https://iiif.io/api/presentation/validator/service/ , or by downloading the validator locally here: https://github.com/IIIF/presentation-validator . 

URL Tested: https://imagehub.vlaamsekunstcollectie.be/iiif/2/kmska.be:410/manifest.json
Validation Error: Every resource must have @type
Warnings:
URL does not have correct access-control-allow-origin header: got "", expected *
The remote server did not use the requested gzip transfer compression, which will slow access. (Content-Encoding: )

every resource must have a type. For the imagehub, this type should always be:
"@type": "dctypes:Image"
for more info check https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/vocabulary/DCTypes.html 

Furthermore CORS isn't configured correctly, this should be changed in the Imagehub to conform how CORS has been configured in the Datahub. You should use nelmio/CORS, you can find how it is configured in the config.yml of the datahub .

**Comment by Kitania** [comment]
CORS has been fixed in 4cb9e4f

GZIP compression has been added in 9016c68, this requires Nginx configuration changes.

All other warnings have been fixed in cc7e5f6
The only thing I'm not sure about is what to do when there is no description of the artwork in the Datahub. Currently, I substitute an empty description with the title to satisfy IIIF specifications, but it doesn't seem right (on the other hand, just adding a blank space, " ", doesn't seem right either).

**Comment by Hobbesball** [comment]
Thanks for the fixes!
When there is no description of the artwork in the datahub, the manifest field should be filled with "n/a" to show that there is no data available for that field.

**Comment by Kitania** [comment]
Fixed in 7303f07

**Comment by Hobbesball** [comment]
reviewed and approved
