### ISSUE TITLE
Validate files in drop folder before uploading to resourcespace

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub#8]
**Detailed description of the issue.**
Images need to be in the correct file format before being uploaded to resourcespace, to ensure a predictable upload process to resourcespace. This validation also ensures that the images in the drop folder are suitable for ingestion by cantaloupe image server. 

**Additional context**
Images need to be :
- in PTIF format
- without extension
- JPEG compressed

If an image is not in the desired extension, do one of two things: 
- either skip the uploading of the image and output a warning that a certain image is not in the right file format
- qeue the image to be processed after the rest of the fillresourcespace command has run, and use imagemagick to convert the image to the correct format, so it will be uploaded in the next run. Output to logfile that an image was not in the correct format, and has been changed to fix that. The generic imagemagick command to put images in the correct format is: 

`convert inputImage -define tiff:tile-geometry=256x256 -compress jpeg ptif:outputimage`

instead of using convert in your program, make sure to use [mogrify](http://www.imagemagick.org/Usage/basics/#mogrify) so images are edited in-line and keep their filename.

**Possible implementation**
images can be identified using the imagemagick identify command. Checking if there's no extension and if it is PTIF is pretty standard information. Discovering how it was compressed can be done with imagemagick with the following command

`magick imagetitle -format "%[compression]" info:`
more info [here](http://www.imagemagick.org/discourse-server/viewtopic.php?t=31192)

**Comment by Kitania** [comment]
Partially fixed in 20d8b34

I added validation to check if the filename does not contain an extension.

As for compression, none of the images appear to have any kind of compression. I have tried two different command line tools, as well as the Imagick PHP library, they all tell me the compression type is "none".

I also can't see any of the images being in PTIF format. Whatever tool I use, everything tells me that the image type is "TIFF" (or "image/tiff").

Aside from that, there is one hurdle in implementing auto-conversion to the right format: PHP doesn't seem to have any library for mogrify. The only viable solution for this seems to use 'exec' to do native command line calls.

**Comment by Hobbesball** [comment]
It seems the images in the VPS hadn't been compressed or put as PTIFS yet when I wrote this issue, that's my bad! Currently all images should both be PTIF and should be JPEG-compressed, **Except for one, which is PTIF but isn't JPEG compressed, for testing purposes**. That image has filename 100000001. 

@netsensei what do you think of using native CL calls for this task? Do you know of another way to use mogrify here?
